name: Flutter Web
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --web-renderer canvaskit
      - name: Update my-file.json description
        uses: jossef/action-set-json-field@v2.1
        with:
          file: ./build/web/version.json
          field: version
          value: ${{ env.RELEASE_VERSION }}
         with:
          file: ./build/web/version.json
          field: version2
          value: ${{ env.RELEASE_VERSION }}
      - name: SyncFtp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: aj0c0.ftp.infomaniak.com
          username: aj0c0_seb
          password: Seb%110978
          local-dir: ./build/web/
          server-dir:  /sites/shot-tracker.dev.seb-chevre.org/